
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AdditionalService` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AdditionalService
 * 
 */
export type AdditionalServiceModel = runtime.Types.Result.DefaultSelection<Prisma.$AdditionalServicePayload>

export type AggregateAdditionalService = {
  _count: AdditionalServiceCountAggregateOutputType | null
  _avg: AdditionalServiceAvgAggregateOutputType | null
  _sum: AdditionalServiceSumAggregateOutputType | null
  _min: AdditionalServiceMinAggregateOutputType | null
  _max: AdditionalServiceMaxAggregateOutputType | null
}

export type AdditionalServiceAvgAggregateOutputType = {
  price: number | null
}

export type AdditionalServiceSumAggregateOutputType = {
  price: number | null
}

export type AdditionalServiceMinAggregateOutputType = {
  id: string | null
  name: string | null
  price: number | null
  active: boolean | null
}

export type AdditionalServiceMaxAggregateOutputType = {
  id: string | null
  name: string | null
  price: number | null
  active: boolean | null
}

export type AdditionalServiceCountAggregateOutputType = {
  id: number
  name: number
  price: number
  active: number
  _all: number
}


export type AdditionalServiceAvgAggregateInputType = {
  price?: true
}

export type AdditionalServiceSumAggregateInputType = {
  price?: true
}

export type AdditionalServiceMinAggregateInputType = {
  id?: true
  name?: true
  price?: true
  active?: true
}

export type AdditionalServiceMaxAggregateInputType = {
  id?: true
  name?: true
  price?: true
  active?: true
}

export type AdditionalServiceCountAggregateInputType = {
  id?: true
  name?: true
  price?: true
  active?: true
  _all?: true
}

export type AdditionalServiceAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AdditionalService to aggregate.
   */
  where?: Prisma.AdditionalServiceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AdditionalServices to fetch.
   */
  orderBy?: Prisma.AdditionalServiceOrderByWithRelationInput | Prisma.AdditionalServiceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AdditionalServiceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AdditionalServices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AdditionalServices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AdditionalServices
  **/
  _count?: true | AdditionalServiceCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AdditionalServiceAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AdditionalServiceSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AdditionalServiceMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AdditionalServiceMaxAggregateInputType
}

export type GetAdditionalServiceAggregateType<T extends AdditionalServiceAggregateArgs> = {
      [P in keyof T & keyof AggregateAdditionalService]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAdditionalService[P]>
    : Prisma.GetScalarType<T[P], AggregateAdditionalService[P]>
}




export type AdditionalServiceGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AdditionalServiceWhereInput
  orderBy?: Prisma.AdditionalServiceOrderByWithAggregationInput | Prisma.AdditionalServiceOrderByWithAggregationInput[]
  by: Prisma.AdditionalServiceScalarFieldEnum[] | Prisma.AdditionalServiceScalarFieldEnum
  having?: Prisma.AdditionalServiceScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AdditionalServiceCountAggregateInputType | true
  _avg?: AdditionalServiceAvgAggregateInputType
  _sum?: AdditionalServiceSumAggregateInputType
  _min?: AdditionalServiceMinAggregateInputType
  _max?: AdditionalServiceMaxAggregateInputType
}

export type AdditionalServiceGroupByOutputType = {
  id: string
  name: string
  price: number
  active: boolean
  _count: AdditionalServiceCountAggregateOutputType | null
  _avg: AdditionalServiceAvgAggregateOutputType | null
  _sum: AdditionalServiceSumAggregateOutputType | null
  _min: AdditionalServiceMinAggregateOutputType | null
  _max: AdditionalServiceMaxAggregateOutputType | null
}

export type GetAdditionalServiceGroupByPayload<T extends AdditionalServiceGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AdditionalServiceGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AdditionalServiceGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AdditionalServiceGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AdditionalServiceGroupByOutputType[P]>
      }
    >
  >



export type AdditionalServiceWhereInput = {
  AND?: Prisma.AdditionalServiceWhereInput | Prisma.AdditionalServiceWhereInput[]
  OR?: Prisma.AdditionalServiceWhereInput[]
  NOT?: Prisma.AdditionalServiceWhereInput | Prisma.AdditionalServiceWhereInput[]
  id?: Prisma.StringFilter<"AdditionalService"> | string
  name?: Prisma.StringFilter<"AdditionalService"> | string
  price?: Prisma.FloatFilter<"AdditionalService"> | number
  active?: Prisma.BoolFilter<"AdditionalService"> | boolean
  bookings?: Prisma.BookingServiceListRelationFilter
}

export type AdditionalServiceOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  price?: Prisma.SortOrder
  active?: Prisma.SortOrder
  bookings?: Prisma.BookingServiceOrderByRelationAggregateInput
}

export type AdditionalServiceWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AdditionalServiceWhereInput | Prisma.AdditionalServiceWhereInput[]
  OR?: Prisma.AdditionalServiceWhereInput[]
  NOT?: Prisma.AdditionalServiceWhereInput | Prisma.AdditionalServiceWhereInput[]
  name?: Prisma.StringFilter<"AdditionalService"> | string
  price?: Prisma.FloatFilter<"AdditionalService"> | number
  active?: Prisma.BoolFilter<"AdditionalService"> | boolean
  bookings?: Prisma.BookingServiceListRelationFilter
}, "id">

export type AdditionalServiceOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  price?: Prisma.SortOrder
  active?: Prisma.SortOrder
  _count?: Prisma.AdditionalServiceCountOrderByAggregateInput
  _avg?: Prisma.AdditionalServiceAvgOrderByAggregateInput
  _max?: Prisma.AdditionalServiceMaxOrderByAggregateInput
  _min?: Prisma.AdditionalServiceMinOrderByAggregateInput
  _sum?: Prisma.AdditionalServiceSumOrderByAggregateInput
}

export type AdditionalServiceScalarWhereWithAggregatesInput = {
  AND?: Prisma.AdditionalServiceScalarWhereWithAggregatesInput | Prisma.AdditionalServiceScalarWhereWithAggregatesInput[]
  OR?: Prisma.AdditionalServiceScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AdditionalServiceScalarWhereWithAggregatesInput | Prisma.AdditionalServiceScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AdditionalService"> | string
  name?: Prisma.StringWithAggregatesFilter<"AdditionalService"> | string
  price?: Prisma.FloatWithAggregatesFilter<"AdditionalService"> | number
  active?: Prisma.BoolWithAggregatesFilter<"AdditionalService"> | boolean
}

export type AdditionalServiceCreateInput = {
  id?: string
  name: string
  price: number
  active?: boolean
  bookings?: Prisma.BookingServiceCreateNestedManyWithoutServiceInput
}

export type AdditionalServiceUncheckedCreateInput = {
  id?: string
  name: string
  price: number
  active?: boolean
  bookings?: Prisma.BookingServiceUncheckedCreateNestedManyWithoutServiceInput
}

export type AdditionalServiceUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  bookings?: Prisma.BookingServiceUpdateManyWithoutServiceNestedInput
}

export type AdditionalServiceUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  bookings?: Prisma.BookingServiceUncheckedUpdateManyWithoutServiceNestedInput
}

export type AdditionalServiceCreateManyInput = {
  id?: string
  name: string
  price: number
  active?: boolean
}

export type AdditionalServiceUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type AdditionalServiceUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type AdditionalServiceCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  price?: Prisma.SortOrder
  active?: Prisma.SortOrder
}

export type AdditionalServiceAvgOrderByAggregateInput = {
  price?: Prisma.SortOrder
}

export type AdditionalServiceMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  price?: Prisma.SortOrder
  active?: Prisma.SortOrder
}

export type AdditionalServiceMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  price?: Prisma.SortOrder
  active?: Prisma.SortOrder
}

export type AdditionalServiceSumOrderByAggregateInput = {
  price?: Prisma.SortOrder
}

export type AdditionalServiceScalarRelationFilter = {
  is?: Prisma.AdditionalServiceWhereInput
  isNot?: Prisma.AdditionalServiceWhereInput
}

export type AdditionalServiceCreateNestedOneWithoutBookingsInput = {
  create?: Prisma.XOR<Prisma.AdditionalServiceCreateWithoutBookingsInput, Prisma.AdditionalServiceUncheckedCreateWithoutBookingsInput>
  connectOrCreate?: Prisma.AdditionalServiceCreateOrConnectWithoutBookingsInput
  connect?: Prisma.AdditionalServiceWhereUniqueInput
}

export type AdditionalServiceUpdateOneRequiredWithoutBookingsNestedInput = {
  create?: Prisma.XOR<Prisma.AdditionalServiceCreateWithoutBookingsInput, Prisma.AdditionalServiceUncheckedCreateWithoutBookingsInput>
  connectOrCreate?: Prisma.AdditionalServiceCreateOrConnectWithoutBookingsInput
  upsert?: Prisma.AdditionalServiceUpsertWithoutBookingsInput
  connect?: Prisma.AdditionalServiceWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AdditionalServiceUpdateToOneWithWhereWithoutBookingsInput, Prisma.AdditionalServiceUpdateWithoutBookingsInput>, Prisma.AdditionalServiceUncheckedUpdateWithoutBookingsInput>
}

export type AdditionalServiceCreateWithoutBookingsInput = {
  id?: string
  name: string
  price: number
  active?: boolean
}

export type AdditionalServiceUncheckedCreateWithoutBookingsInput = {
  id?: string
  name: string
  price: number
  active?: boolean
}

export type AdditionalServiceCreateOrConnectWithoutBookingsInput = {
  where: Prisma.AdditionalServiceWhereUniqueInput
  create: Prisma.XOR<Prisma.AdditionalServiceCreateWithoutBookingsInput, Prisma.AdditionalServiceUncheckedCreateWithoutBookingsInput>
}

export type AdditionalServiceUpsertWithoutBookingsInput = {
  update: Prisma.XOR<Prisma.AdditionalServiceUpdateWithoutBookingsInput, Prisma.AdditionalServiceUncheckedUpdateWithoutBookingsInput>
  create: Prisma.XOR<Prisma.AdditionalServiceCreateWithoutBookingsInput, Prisma.AdditionalServiceUncheckedCreateWithoutBookingsInput>
  where?: Prisma.AdditionalServiceWhereInput
}

export type AdditionalServiceUpdateToOneWithWhereWithoutBookingsInput = {
  where?: Prisma.AdditionalServiceWhereInput
  data: Prisma.XOR<Prisma.AdditionalServiceUpdateWithoutBookingsInput, Prisma.AdditionalServiceUncheckedUpdateWithoutBookingsInput>
}

export type AdditionalServiceUpdateWithoutBookingsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type AdditionalServiceUncheckedUpdateWithoutBookingsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.FloatFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
}


/**
 * Count Type AdditionalServiceCountOutputType
 */

export type AdditionalServiceCountOutputType = {
  bookings: number
}

export type AdditionalServiceCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bookings?: boolean | AdditionalServiceCountOutputTypeCountBookingsArgs
}

/**
 * AdditionalServiceCountOutputType without action
 */
export type AdditionalServiceCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdditionalServiceCountOutputType
   */
  select?: Prisma.AdditionalServiceCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AdditionalServiceCountOutputType without action
 */
export type AdditionalServiceCountOutputTypeCountBookingsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BookingServiceWhereInput
}


export type AdditionalServiceSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  price?: boolean
  active?: boolean
  bookings?: boolean | Prisma.AdditionalService$bookingsArgs<ExtArgs>
  _count?: boolean | Prisma.AdditionalServiceCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["additionalService"]>

export type AdditionalServiceSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  price?: boolean
  active?: boolean
}, ExtArgs["result"]["additionalService"]>

export type AdditionalServiceSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  price?: boolean
  active?: boolean
}, ExtArgs["result"]["additionalService"]>

export type AdditionalServiceSelectScalar = {
  id?: boolean
  name?: boolean
  price?: boolean
  active?: boolean
}

export type AdditionalServiceOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "price" | "active", ExtArgs["result"]["additionalService"]>
export type AdditionalServiceInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bookings?: boolean | Prisma.AdditionalService$bookingsArgs<ExtArgs>
  _count?: boolean | Prisma.AdditionalServiceCountOutputTypeDefaultArgs<ExtArgs>
}
export type AdditionalServiceIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type AdditionalServiceIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $AdditionalServicePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AdditionalService"
  objects: {
    bookings: Prisma.$BookingServicePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    price: number
    active: boolean
  }, ExtArgs["result"]["additionalService"]>
  composites: {}
}

export type AdditionalServiceGetPayload<S extends boolean | null | undefined | AdditionalServiceDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AdditionalServicePayload, S>

export type AdditionalServiceCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AdditionalServiceFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AdditionalServiceCountAggregateInputType | true
  }

export interface AdditionalServiceDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AdditionalService'], meta: { name: 'AdditionalService' } }
  /**
   * Find zero or one AdditionalService that matches the filter.
   * @param {AdditionalServiceFindUniqueArgs} args - Arguments to find a AdditionalService
   * @example
   * // Get one AdditionalService
   * const additionalService = await prisma.additionalService.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AdditionalServiceFindUniqueArgs>(args: Prisma.SelectSubset<T, AdditionalServiceFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AdditionalServiceClient<runtime.Types.Result.GetResult<Prisma.$AdditionalServicePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AdditionalService that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AdditionalServiceFindUniqueOrThrowArgs} args - Arguments to find a AdditionalService
   * @example
   * // Get one AdditionalService
   * const additionalService = await prisma.additionalService.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AdditionalServiceFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AdditionalServiceFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AdditionalServiceClient<runtime.Types.Result.GetResult<Prisma.$AdditionalServicePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AdditionalService that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdditionalServiceFindFirstArgs} args - Arguments to find a AdditionalService
   * @example
   * // Get one AdditionalService
   * const additionalService = await prisma.additionalService.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AdditionalServiceFindFirstArgs>(args?: Prisma.SelectSubset<T, AdditionalServiceFindFirstArgs<ExtArgs>>): Prisma.Prisma__AdditionalServiceClient<runtime.Types.Result.GetResult<Prisma.$AdditionalServicePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AdditionalService that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdditionalServiceFindFirstOrThrowArgs} args - Arguments to find a AdditionalService
   * @example
   * // Get one AdditionalService
   * const additionalService = await prisma.additionalService.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AdditionalServiceFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AdditionalServiceFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AdditionalServiceClient<runtime.Types.Result.GetResult<Prisma.$AdditionalServicePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AdditionalServices that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdditionalServiceFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AdditionalServices
   * const additionalServices = await prisma.additionalService.findMany()
   * 
   * // Get first 10 AdditionalServices
   * const additionalServices = await prisma.additionalService.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const additionalServiceWithIdOnly = await prisma.additionalService.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AdditionalServiceFindManyArgs>(args?: Prisma.SelectSubset<T, AdditionalServiceFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AdditionalServicePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AdditionalService.
   * @param {AdditionalServiceCreateArgs} args - Arguments to create a AdditionalService.
   * @example
   * // Create one AdditionalService
   * const AdditionalService = await prisma.additionalService.create({
   *   data: {
   *     // ... data to create a AdditionalService
   *   }
   * })
   * 
   */
  create<T extends AdditionalServiceCreateArgs>(args: Prisma.SelectSubset<T, AdditionalServiceCreateArgs<ExtArgs>>): Prisma.Prisma__AdditionalServiceClient<runtime.Types.Result.GetResult<Prisma.$AdditionalServicePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AdditionalServices.
   * @param {AdditionalServiceCreateManyArgs} args - Arguments to create many AdditionalServices.
   * @example
   * // Create many AdditionalServices
   * const additionalService = await prisma.additionalService.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AdditionalServiceCreateManyArgs>(args?: Prisma.SelectSubset<T, AdditionalServiceCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AdditionalServices and returns the data saved in the database.
   * @param {AdditionalServiceCreateManyAndReturnArgs} args - Arguments to create many AdditionalServices.
   * @example
   * // Create many AdditionalServices
   * const additionalService = await prisma.additionalService.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AdditionalServices and only return the `id`
   * const additionalServiceWithIdOnly = await prisma.additionalService.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AdditionalServiceCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AdditionalServiceCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AdditionalServicePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AdditionalService.
   * @param {AdditionalServiceDeleteArgs} args - Arguments to delete one AdditionalService.
   * @example
   * // Delete one AdditionalService
   * const AdditionalService = await prisma.additionalService.delete({
   *   where: {
   *     // ... filter to delete one AdditionalService
   *   }
   * })
   * 
   */
  delete<T extends AdditionalServiceDeleteArgs>(args: Prisma.SelectSubset<T, AdditionalServiceDeleteArgs<ExtArgs>>): Prisma.Prisma__AdditionalServiceClient<runtime.Types.Result.GetResult<Prisma.$AdditionalServicePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AdditionalService.
   * @param {AdditionalServiceUpdateArgs} args - Arguments to update one AdditionalService.
   * @example
   * // Update one AdditionalService
   * const additionalService = await prisma.additionalService.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AdditionalServiceUpdateArgs>(args: Prisma.SelectSubset<T, AdditionalServiceUpdateArgs<ExtArgs>>): Prisma.Prisma__AdditionalServiceClient<runtime.Types.Result.GetResult<Prisma.$AdditionalServicePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AdditionalServices.
   * @param {AdditionalServiceDeleteManyArgs} args - Arguments to filter AdditionalServices to delete.
   * @example
   * // Delete a few AdditionalServices
   * const { count } = await prisma.additionalService.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AdditionalServiceDeleteManyArgs>(args?: Prisma.SelectSubset<T, AdditionalServiceDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AdditionalServices.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdditionalServiceUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AdditionalServices
   * const additionalService = await prisma.additionalService.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AdditionalServiceUpdateManyArgs>(args: Prisma.SelectSubset<T, AdditionalServiceUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AdditionalServices and returns the data updated in the database.
   * @param {AdditionalServiceUpdateManyAndReturnArgs} args - Arguments to update many AdditionalServices.
   * @example
   * // Update many AdditionalServices
   * const additionalService = await prisma.additionalService.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AdditionalServices and only return the `id`
   * const additionalServiceWithIdOnly = await prisma.additionalService.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AdditionalServiceUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AdditionalServiceUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AdditionalServicePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AdditionalService.
   * @param {AdditionalServiceUpsertArgs} args - Arguments to update or create a AdditionalService.
   * @example
   * // Update or create a AdditionalService
   * const additionalService = await prisma.additionalService.upsert({
   *   create: {
   *     // ... data to create a AdditionalService
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AdditionalService we want to update
   *   }
   * })
   */
  upsert<T extends AdditionalServiceUpsertArgs>(args: Prisma.SelectSubset<T, AdditionalServiceUpsertArgs<ExtArgs>>): Prisma.Prisma__AdditionalServiceClient<runtime.Types.Result.GetResult<Prisma.$AdditionalServicePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AdditionalServices.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdditionalServiceCountArgs} args - Arguments to filter AdditionalServices to count.
   * @example
   * // Count the number of AdditionalServices
   * const count = await prisma.additionalService.count({
   *   where: {
   *     // ... the filter for the AdditionalServices we want to count
   *   }
   * })
  **/
  count<T extends AdditionalServiceCountArgs>(
    args?: Prisma.Subset<T, AdditionalServiceCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AdditionalServiceCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AdditionalService.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdditionalServiceAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AdditionalServiceAggregateArgs>(args: Prisma.Subset<T, AdditionalServiceAggregateArgs>): Prisma.PrismaPromise<GetAdditionalServiceAggregateType<T>>

  /**
   * Group by AdditionalService.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdditionalServiceGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AdditionalServiceGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AdditionalServiceGroupByArgs['orderBy'] }
      : { orderBy?: AdditionalServiceGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AdditionalServiceGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAdditionalServiceGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AdditionalService model
 */
readonly fields: AdditionalServiceFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AdditionalService.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AdditionalServiceClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  bookings<T extends Prisma.AdditionalService$bookingsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AdditionalService$bookingsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BookingServicePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AdditionalService model
 */
export interface AdditionalServiceFieldRefs {
  readonly id: Prisma.FieldRef<"AdditionalService", 'String'>
  readonly name: Prisma.FieldRef<"AdditionalService", 'String'>
  readonly price: Prisma.FieldRef<"AdditionalService", 'Float'>
  readonly active: Prisma.FieldRef<"AdditionalService", 'Boolean'>
}
    

// Custom InputTypes
/**
 * AdditionalService findUnique
 */
export type AdditionalServiceFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdditionalService
   */
  select?: Prisma.AdditionalServiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdditionalService
   */
  omit?: Prisma.AdditionalServiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdditionalServiceInclude<ExtArgs> | null
  /**
   * Filter, which AdditionalService to fetch.
   */
  where: Prisma.AdditionalServiceWhereUniqueInput
}

/**
 * AdditionalService findUniqueOrThrow
 */
export type AdditionalServiceFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdditionalService
   */
  select?: Prisma.AdditionalServiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdditionalService
   */
  omit?: Prisma.AdditionalServiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdditionalServiceInclude<ExtArgs> | null
  /**
   * Filter, which AdditionalService to fetch.
   */
  where: Prisma.AdditionalServiceWhereUniqueInput
}

/**
 * AdditionalService findFirst
 */
export type AdditionalServiceFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdditionalService
   */
  select?: Prisma.AdditionalServiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdditionalService
   */
  omit?: Prisma.AdditionalServiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdditionalServiceInclude<ExtArgs> | null
  /**
   * Filter, which AdditionalService to fetch.
   */
  where?: Prisma.AdditionalServiceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AdditionalServices to fetch.
   */
  orderBy?: Prisma.AdditionalServiceOrderByWithRelationInput | Prisma.AdditionalServiceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AdditionalServices.
   */
  cursor?: Prisma.AdditionalServiceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AdditionalServices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AdditionalServices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AdditionalServices.
   */
  distinct?: Prisma.AdditionalServiceScalarFieldEnum | Prisma.AdditionalServiceScalarFieldEnum[]
}

/**
 * AdditionalService findFirstOrThrow
 */
export type AdditionalServiceFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdditionalService
   */
  select?: Prisma.AdditionalServiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdditionalService
   */
  omit?: Prisma.AdditionalServiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdditionalServiceInclude<ExtArgs> | null
  /**
   * Filter, which AdditionalService to fetch.
   */
  where?: Prisma.AdditionalServiceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AdditionalServices to fetch.
   */
  orderBy?: Prisma.AdditionalServiceOrderByWithRelationInput | Prisma.AdditionalServiceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AdditionalServices.
   */
  cursor?: Prisma.AdditionalServiceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AdditionalServices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AdditionalServices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AdditionalServices.
   */
  distinct?: Prisma.AdditionalServiceScalarFieldEnum | Prisma.AdditionalServiceScalarFieldEnum[]
}

/**
 * AdditionalService findMany
 */
export type AdditionalServiceFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdditionalService
   */
  select?: Prisma.AdditionalServiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdditionalService
   */
  omit?: Prisma.AdditionalServiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdditionalServiceInclude<ExtArgs> | null
  /**
   * Filter, which AdditionalServices to fetch.
   */
  where?: Prisma.AdditionalServiceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AdditionalServices to fetch.
   */
  orderBy?: Prisma.AdditionalServiceOrderByWithRelationInput | Prisma.AdditionalServiceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AdditionalServices.
   */
  cursor?: Prisma.AdditionalServiceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AdditionalServices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AdditionalServices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AdditionalServices.
   */
  distinct?: Prisma.AdditionalServiceScalarFieldEnum | Prisma.AdditionalServiceScalarFieldEnum[]
}

/**
 * AdditionalService create
 */
export type AdditionalServiceCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdditionalService
   */
  select?: Prisma.AdditionalServiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdditionalService
   */
  omit?: Prisma.AdditionalServiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdditionalServiceInclude<ExtArgs> | null
  /**
   * The data needed to create a AdditionalService.
   */
  data: Prisma.XOR<Prisma.AdditionalServiceCreateInput, Prisma.AdditionalServiceUncheckedCreateInput>
}

/**
 * AdditionalService createMany
 */
export type AdditionalServiceCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AdditionalServices.
   */
  data: Prisma.AdditionalServiceCreateManyInput | Prisma.AdditionalServiceCreateManyInput[]
}

/**
 * AdditionalService createManyAndReturn
 */
export type AdditionalServiceCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdditionalService
   */
  select?: Prisma.AdditionalServiceSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AdditionalService
   */
  omit?: Prisma.AdditionalServiceOmit<ExtArgs> | null
  /**
   * The data used to create many AdditionalServices.
   */
  data: Prisma.AdditionalServiceCreateManyInput | Prisma.AdditionalServiceCreateManyInput[]
}

/**
 * AdditionalService update
 */
export type AdditionalServiceUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdditionalService
   */
  select?: Prisma.AdditionalServiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdditionalService
   */
  omit?: Prisma.AdditionalServiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdditionalServiceInclude<ExtArgs> | null
  /**
   * The data needed to update a AdditionalService.
   */
  data: Prisma.XOR<Prisma.AdditionalServiceUpdateInput, Prisma.AdditionalServiceUncheckedUpdateInput>
  /**
   * Choose, which AdditionalService to update.
   */
  where: Prisma.AdditionalServiceWhereUniqueInput
}

/**
 * AdditionalService updateMany
 */
export type AdditionalServiceUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AdditionalServices.
   */
  data: Prisma.XOR<Prisma.AdditionalServiceUpdateManyMutationInput, Prisma.AdditionalServiceUncheckedUpdateManyInput>
  /**
   * Filter which AdditionalServices to update
   */
  where?: Prisma.AdditionalServiceWhereInput
  /**
   * Limit how many AdditionalServices to update.
   */
  limit?: number
}

/**
 * AdditionalService updateManyAndReturn
 */
export type AdditionalServiceUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdditionalService
   */
  select?: Prisma.AdditionalServiceSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AdditionalService
   */
  omit?: Prisma.AdditionalServiceOmit<ExtArgs> | null
  /**
   * The data used to update AdditionalServices.
   */
  data: Prisma.XOR<Prisma.AdditionalServiceUpdateManyMutationInput, Prisma.AdditionalServiceUncheckedUpdateManyInput>
  /**
   * Filter which AdditionalServices to update
   */
  where?: Prisma.AdditionalServiceWhereInput
  /**
   * Limit how many AdditionalServices to update.
   */
  limit?: number
}

/**
 * AdditionalService upsert
 */
export type AdditionalServiceUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdditionalService
   */
  select?: Prisma.AdditionalServiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdditionalService
   */
  omit?: Prisma.AdditionalServiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdditionalServiceInclude<ExtArgs> | null
  /**
   * The filter to search for the AdditionalService to update in case it exists.
   */
  where: Prisma.AdditionalServiceWhereUniqueInput
  /**
   * In case the AdditionalService found by the `where` argument doesn't exist, create a new AdditionalService with this data.
   */
  create: Prisma.XOR<Prisma.AdditionalServiceCreateInput, Prisma.AdditionalServiceUncheckedCreateInput>
  /**
   * In case the AdditionalService was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AdditionalServiceUpdateInput, Prisma.AdditionalServiceUncheckedUpdateInput>
}

/**
 * AdditionalService delete
 */
export type AdditionalServiceDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdditionalService
   */
  select?: Prisma.AdditionalServiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdditionalService
   */
  omit?: Prisma.AdditionalServiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdditionalServiceInclude<ExtArgs> | null
  /**
   * Filter which AdditionalService to delete.
   */
  where: Prisma.AdditionalServiceWhereUniqueInput
}

/**
 * AdditionalService deleteMany
 */
export type AdditionalServiceDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AdditionalServices to delete
   */
  where?: Prisma.AdditionalServiceWhereInput
  /**
   * Limit how many AdditionalServices to delete.
   */
  limit?: number
}

/**
 * AdditionalService.bookings
 */
export type AdditionalService$bookingsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BookingService
   */
  select?: Prisma.BookingServiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BookingService
   */
  omit?: Prisma.BookingServiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookingServiceInclude<ExtArgs> | null
  where?: Prisma.BookingServiceWhereInput
  orderBy?: Prisma.BookingServiceOrderByWithRelationInput | Prisma.BookingServiceOrderByWithRelationInput[]
  cursor?: Prisma.BookingServiceWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.BookingServiceScalarFieldEnum | Prisma.BookingServiceScalarFieldEnum[]
}

/**
 * AdditionalService without action
 */
export type AdditionalServiceDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdditionalService
   */
  select?: Prisma.AdditionalServiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdditionalService
   */
  omit?: Prisma.AdditionalServiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdditionalServiceInclude<ExtArgs> | null
}
