
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BlockedDay` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model BlockedDay
 * 
 */
export type BlockedDayModel = runtime.Types.Result.DefaultSelection<Prisma.$BlockedDayPayload>

export type AggregateBlockedDay = {
  _count: BlockedDayCountAggregateOutputType | null
  _min: BlockedDayMinAggregateOutputType | null
  _max: BlockedDayMaxAggregateOutputType | null
}

export type BlockedDayMinAggregateOutputType = {
  id: string | null
  date: string | null
  reason: string | null
  createdAt: Date | null
}

export type BlockedDayMaxAggregateOutputType = {
  id: string | null
  date: string | null
  reason: string | null
  createdAt: Date | null
}

export type BlockedDayCountAggregateOutputType = {
  id: number
  date: number
  reason: number
  createdAt: number
  _all: number
}


export type BlockedDayMinAggregateInputType = {
  id?: true
  date?: true
  reason?: true
  createdAt?: true
}

export type BlockedDayMaxAggregateInputType = {
  id?: true
  date?: true
  reason?: true
  createdAt?: true
}

export type BlockedDayCountAggregateInputType = {
  id?: true
  date?: true
  reason?: true
  createdAt?: true
  _all?: true
}

export type BlockedDayAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BlockedDay to aggregate.
   */
  where?: Prisma.BlockedDayWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BlockedDays to fetch.
   */
  orderBy?: Prisma.BlockedDayOrderByWithRelationInput | Prisma.BlockedDayOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BlockedDayWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BlockedDays from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BlockedDays.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BlockedDays
  **/
  _count?: true | BlockedDayCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BlockedDayMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BlockedDayMaxAggregateInputType
}

export type GetBlockedDayAggregateType<T extends BlockedDayAggregateArgs> = {
      [P in keyof T & keyof AggregateBlockedDay]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBlockedDay[P]>
    : Prisma.GetScalarType<T[P], AggregateBlockedDay[P]>
}




export type BlockedDayGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BlockedDayWhereInput
  orderBy?: Prisma.BlockedDayOrderByWithAggregationInput | Prisma.BlockedDayOrderByWithAggregationInput[]
  by: Prisma.BlockedDayScalarFieldEnum[] | Prisma.BlockedDayScalarFieldEnum
  having?: Prisma.BlockedDayScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BlockedDayCountAggregateInputType | true
  _min?: BlockedDayMinAggregateInputType
  _max?: BlockedDayMaxAggregateInputType
}

export type BlockedDayGroupByOutputType = {
  id: string
  date: string
  reason: string | null
  createdAt: Date
  _count: BlockedDayCountAggregateOutputType | null
  _min: BlockedDayMinAggregateOutputType | null
  _max: BlockedDayMaxAggregateOutputType | null
}

export type GetBlockedDayGroupByPayload<T extends BlockedDayGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BlockedDayGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BlockedDayGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BlockedDayGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BlockedDayGroupByOutputType[P]>
      }
    >
  >



export type BlockedDayWhereInput = {
  AND?: Prisma.BlockedDayWhereInput | Prisma.BlockedDayWhereInput[]
  OR?: Prisma.BlockedDayWhereInput[]
  NOT?: Prisma.BlockedDayWhereInput | Prisma.BlockedDayWhereInput[]
  id?: Prisma.StringFilter<"BlockedDay"> | string
  date?: Prisma.StringFilter<"BlockedDay"> | string
  reason?: Prisma.StringNullableFilter<"BlockedDay"> | string | null
  createdAt?: Prisma.DateTimeFilter<"BlockedDay"> | Date | string
}

export type BlockedDayOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  reason?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type BlockedDayWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  date?: string
  AND?: Prisma.BlockedDayWhereInput | Prisma.BlockedDayWhereInput[]
  OR?: Prisma.BlockedDayWhereInput[]
  NOT?: Prisma.BlockedDayWhereInput | Prisma.BlockedDayWhereInput[]
  reason?: Prisma.StringNullableFilter<"BlockedDay"> | string | null
  createdAt?: Prisma.DateTimeFilter<"BlockedDay"> | Date | string
}, "id" | "date">

export type BlockedDayOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  reason?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.BlockedDayCountOrderByAggregateInput
  _max?: Prisma.BlockedDayMaxOrderByAggregateInput
  _min?: Prisma.BlockedDayMinOrderByAggregateInput
}

export type BlockedDayScalarWhereWithAggregatesInput = {
  AND?: Prisma.BlockedDayScalarWhereWithAggregatesInput | Prisma.BlockedDayScalarWhereWithAggregatesInput[]
  OR?: Prisma.BlockedDayScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BlockedDayScalarWhereWithAggregatesInput | Prisma.BlockedDayScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"BlockedDay"> | string
  date?: Prisma.StringWithAggregatesFilter<"BlockedDay"> | string
  reason?: Prisma.StringNullableWithAggregatesFilter<"BlockedDay"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"BlockedDay"> | Date | string
}

export type BlockedDayCreateInput = {
  id?: string
  date: string
  reason?: string | null
  createdAt?: Date | string
}

export type BlockedDayUncheckedCreateInput = {
  id?: string
  date: string
  reason?: string | null
  createdAt?: Date | string
}

export type BlockedDayUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BlockedDayUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BlockedDayCreateManyInput = {
  id?: string
  date: string
  reason?: string | null
  createdAt?: Date | string
}

export type BlockedDayUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BlockedDayUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BlockedDayCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type BlockedDayMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type BlockedDayMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}



export type BlockedDaySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  reason?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["blockedDay"]>

export type BlockedDaySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  reason?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["blockedDay"]>

export type BlockedDaySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  reason?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["blockedDay"]>

export type BlockedDaySelectScalar = {
  id?: boolean
  date?: boolean
  reason?: boolean
  createdAt?: boolean
}

export type BlockedDayOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "date" | "reason" | "createdAt", ExtArgs["result"]["blockedDay"]>

export type $BlockedDayPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BlockedDay"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    date: string
    reason: string | null
    createdAt: Date
  }, ExtArgs["result"]["blockedDay"]>
  composites: {}
}

export type BlockedDayGetPayload<S extends boolean | null | undefined | BlockedDayDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BlockedDayPayload, S>

export type BlockedDayCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BlockedDayFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BlockedDayCountAggregateInputType | true
  }

export interface BlockedDayDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BlockedDay'], meta: { name: 'BlockedDay' } }
  /**
   * Find zero or one BlockedDay that matches the filter.
   * @param {BlockedDayFindUniqueArgs} args - Arguments to find a BlockedDay
   * @example
   * // Get one BlockedDay
   * const blockedDay = await prisma.blockedDay.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BlockedDayFindUniqueArgs>(args: Prisma.SelectSubset<T, BlockedDayFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BlockedDayClient<runtime.Types.Result.GetResult<Prisma.$BlockedDayPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BlockedDay that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BlockedDayFindUniqueOrThrowArgs} args - Arguments to find a BlockedDay
   * @example
   * // Get one BlockedDay
   * const blockedDay = await prisma.blockedDay.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BlockedDayFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BlockedDayFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BlockedDayClient<runtime.Types.Result.GetResult<Prisma.$BlockedDayPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BlockedDay that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BlockedDayFindFirstArgs} args - Arguments to find a BlockedDay
   * @example
   * // Get one BlockedDay
   * const blockedDay = await prisma.blockedDay.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BlockedDayFindFirstArgs>(args?: Prisma.SelectSubset<T, BlockedDayFindFirstArgs<ExtArgs>>): Prisma.Prisma__BlockedDayClient<runtime.Types.Result.GetResult<Prisma.$BlockedDayPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BlockedDay that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BlockedDayFindFirstOrThrowArgs} args - Arguments to find a BlockedDay
   * @example
   * // Get one BlockedDay
   * const blockedDay = await prisma.blockedDay.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BlockedDayFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BlockedDayFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BlockedDayClient<runtime.Types.Result.GetResult<Prisma.$BlockedDayPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BlockedDays that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BlockedDayFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BlockedDays
   * const blockedDays = await prisma.blockedDay.findMany()
   * 
   * // Get first 10 BlockedDays
   * const blockedDays = await prisma.blockedDay.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const blockedDayWithIdOnly = await prisma.blockedDay.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BlockedDayFindManyArgs>(args?: Prisma.SelectSubset<T, BlockedDayFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BlockedDayPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BlockedDay.
   * @param {BlockedDayCreateArgs} args - Arguments to create a BlockedDay.
   * @example
   * // Create one BlockedDay
   * const BlockedDay = await prisma.blockedDay.create({
   *   data: {
   *     // ... data to create a BlockedDay
   *   }
   * })
   * 
   */
  create<T extends BlockedDayCreateArgs>(args: Prisma.SelectSubset<T, BlockedDayCreateArgs<ExtArgs>>): Prisma.Prisma__BlockedDayClient<runtime.Types.Result.GetResult<Prisma.$BlockedDayPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BlockedDays.
   * @param {BlockedDayCreateManyArgs} args - Arguments to create many BlockedDays.
   * @example
   * // Create many BlockedDays
   * const blockedDay = await prisma.blockedDay.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BlockedDayCreateManyArgs>(args?: Prisma.SelectSubset<T, BlockedDayCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BlockedDays and returns the data saved in the database.
   * @param {BlockedDayCreateManyAndReturnArgs} args - Arguments to create many BlockedDays.
   * @example
   * // Create many BlockedDays
   * const blockedDay = await prisma.blockedDay.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BlockedDays and only return the `id`
   * const blockedDayWithIdOnly = await prisma.blockedDay.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BlockedDayCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BlockedDayCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BlockedDayPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BlockedDay.
   * @param {BlockedDayDeleteArgs} args - Arguments to delete one BlockedDay.
   * @example
   * // Delete one BlockedDay
   * const BlockedDay = await prisma.blockedDay.delete({
   *   where: {
   *     // ... filter to delete one BlockedDay
   *   }
   * })
   * 
   */
  delete<T extends BlockedDayDeleteArgs>(args: Prisma.SelectSubset<T, BlockedDayDeleteArgs<ExtArgs>>): Prisma.Prisma__BlockedDayClient<runtime.Types.Result.GetResult<Prisma.$BlockedDayPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BlockedDay.
   * @param {BlockedDayUpdateArgs} args - Arguments to update one BlockedDay.
   * @example
   * // Update one BlockedDay
   * const blockedDay = await prisma.blockedDay.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BlockedDayUpdateArgs>(args: Prisma.SelectSubset<T, BlockedDayUpdateArgs<ExtArgs>>): Prisma.Prisma__BlockedDayClient<runtime.Types.Result.GetResult<Prisma.$BlockedDayPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BlockedDays.
   * @param {BlockedDayDeleteManyArgs} args - Arguments to filter BlockedDays to delete.
   * @example
   * // Delete a few BlockedDays
   * const { count } = await prisma.blockedDay.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BlockedDayDeleteManyArgs>(args?: Prisma.SelectSubset<T, BlockedDayDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BlockedDays.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BlockedDayUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BlockedDays
   * const blockedDay = await prisma.blockedDay.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BlockedDayUpdateManyArgs>(args: Prisma.SelectSubset<T, BlockedDayUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BlockedDays and returns the data updated in the database.
   * @param {BlockedDayUpdateManyAndReturnArgs} args - Arguments to update many BlockedDays.
   * @example
   * // Update many BlockedDays
   * const blockedDay = await prisma.blockedDay.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BlockedDays and only return the `id`
   * const blockedDayWithIdOnly = await prisma.blockedDay.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BlockedDayUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BlockedDayUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BlockedDayPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BlockedDay.
   * @param {BlockedDayUpsertArgs} args - Arguments to update or create a BlockedDay.
   * @example
   * // Update or create a BlockedDay
   * const blockedDay = await prisma.blockedDay.upsert({
   *   create: {
   *     // ... data to create a BlockedDay
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BlockedDay we want to update
   *   }
   * })
   */
  upsert<T extends BlockedDayUpsertArgs>(args: Prisma.SelectSubset<T, BlockedDayUpsertArgs<ExtArgs>>): Prisma.Prisma__BlockedDayClient<runtime.Types.Result.GetResult<Prisma.$BlockedDayPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BlockedDays.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BlockedDayCountArgs} args - Arguments to filter BlockedDays to count.
   * @example
   * // Count the number of BlockedDays
   * const count = await prisma.blockedDay.count({
   *   where: {
   *     // ... the filter for the BlockedDays we want to count
   *   }
   * })
  **/
  count<T extends BlockedDayCountArgs>(
    args?: Prisma.Subset<T, BlockedDayCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BlockedDayCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BlockedDay.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BlockedDayAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BlockedDayAggregateArgs>(args: Prisma.Subset<T, BlockedDayAggregateArgs>): Prisma.PrismaPromise<GetBlockedDayAggregateType<T>>

  /**
   * Group by BlockedDay.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BlockedDayGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BlockedDayGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BlockedDayGroupByArgs['orderBy'] }
      : { orderBy?: BlockedDayGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BlockedDayGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBlockedDayGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BlockedDay model
 */
readonly fields: BlockedDayFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BlockedDay.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BlockedDayClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BlockedDay model
 */
export interface BlockedDayFieldRefs {
  readonly id: Prisma.FieldRef<"BlockedDay", 'String'>
  readonly date: Prisma.FieldRef<"BlockedDay", 'String'>
  readonly reason: Prisma.FieldRef<"BlockedDay", 'String'>
  readonly createdAt: Prisma.FieldRef<"BlockedDay", 'DateTime'>
}
    

// Custom InputTypes
/**
 * BlockedDay findUnique
 */
export type BlockedDayFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlockedDay
   */
  select?: Prisma.BlockedDaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the BlockedDay
   */
  omit?: Prisma.BlockedDayOmit<ExtArgs> | null
  /**
   * Filter, which BlockedDay to fetch.
   */
  where: Prisma.BlockedDayWhereUniqueInput
}

/**
 * BlockedDay findUniqueOrThrow
 */
export type BlockedDayFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlockedDay
   */
  select?: Prisma.BlockedDaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the BlockedDay
   */
  omit?: Prisma.BlockedDayOmit<ExtArgs> | null
  /**
   * Filter, which BlockedDay to fetch.
   */
  where: Prisma.BlockedDayWhereUniqueInput
}

/**
 * BlockedDay findFirst
 */
export type BlockedDayFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlockedDay
   */
  select?: Prisma.BlockedDaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the BlockedDay
   */
  omit?: Prisma.BlockedDayOmit<ExtArgs> | null
  /**
   * Filter, which BlockedDay to fetch.
   */
  where?: Prisma.BlockedDayWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BlockedDays to fetch.
   */
  orderBy?: Prisma.BlockedDayOrderByWithRelationInput | Prisma.BlockedDayOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BlockedDays.
   */
  cursor?: Prisma.BlockedDayWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BlockedDays from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BlockedDays.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BlockedDays.
   */
  distinct?: Prisma.BlockedDayScalarFieldEnum | Prisma.BlockedDayScalarFieldEnum[]
}

/**
 * BlockedDay findFirstOrThrow
 */
export type BlockedDayFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlockedDay
   */
  select?: Prisma.BlockedDaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the BlockedDay
   */
  omit?: Prisma.BlockedDayOmit<ExtArgs> | null
  /**
   * Filter, which BlockedDay to fetch.
   */
  where?: Prisma.BlockedDayWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BlockedDays to fetch.
   */
  orderBy?: Prisma.BlockedDayOrderByWithRelationInput | Prisma.BlockedDayOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BlockedDays.
   */
  cursor?: Prisma.BlockedDayWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BlockedDays from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BlockedDays.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BlockedDays.
   */
  distinct?: Prisma.BlockedDayScalarFieldEnum | Prisma.BlockedDayScalarFieldEnum[]
}

/**
 * BlockedDay findMany
 */
export type BlockedDayFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlockedDay
   */
  select?: Prisma.BlockedDaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the BlockedDay
   */
  omit?: Prisma.BlockedDayOmit<ExtArgs> | null
  /**
   * Filter, which BlockedDays to fetch.
   */
  where?: Prisma.BlockedDayWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BlockedDays to fetch.
   */
  orderBy?: Prisma.BlockedDayOrderByWithRelationInput | Prisma.BlockedDayOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BlockedDays.
   */
  cursor?: Prisma.BlockedDayWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BlockedDays from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BlockedDays.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BlockedDays.
   */
  distinct?: Prisma.BlockedDayScalarFieldEnum | Prisma.BlockedDayScalarFieldEnum[]
}

/**
 * BlockedDay create
 */
export type BlockedDayCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlockedDay
   */
  select?: Prisma.BlockedDaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the BlockedDay
   */
  omit?: Prisma.BlockedDayOmit<ExtArgs> | null
  /**
   * The data needed to create a BlockedDay.
   */
  data: Prisma.XOR<Prisma.BlockedDayCreateInput, Prisma.BlockedDayUncheckedCreateInput>
}

/**
 * BlockedDay createMany
 */
export type BlockedDayCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BlockedDays.
   */
  data: Prisma.BlockedDayCreateManyInput | Prisma.BlockedDayCreateManyInput[]
}

/**
 * BlockedDay createManyAndReturn
 */
export type BlockedDayCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlockedDay
   */
  select?: Prisma.BlockedDaySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BlockedDay
   */
  omit?: Prisma.BlockedDayOmit<ExtArgs> | null
  /**
   * The data used to create many BlockedDays.
   */
  data: Prisma.BlockedDayCreateManyInput | Prisma.BlockedDayCreateManyInput[]
}

/**
 * BlockedDay update
 */
export type BlockedDayUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlockedDay
   */
  select?: Prisma.BlockedDaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the BlockedDay
   */
  omit?: Prisma.BlockedDayOmit<ExtArgs> | null
  /**
   * The data needed to update a BlockedDay.
   */
  data: Prisma.XOR<Prisma.BlockedDayUpdateInput, Prisma.BlockedDayUncheckedUpdateInput>
  /**
   * Choose, which BlockedDay to update.
   */
  where: Prisma.BlockedDayWhereUniqueInput
}

/**
 * BlockedDay updateMany
 */
export type BlockedDayUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BlockedDays.
   */
  data: Prisma.XOR<Prisma.BlockedDayUpdateManyMutationInput, Prisma.BlockedDayUncheckedUpdateManyInput>
  /**
   * Filter which BlockedDays to update
   */
  where?: Prisma.BlockedDayWhereInput
  /**
   * Limit how many BlockedDays to update.
   */
  limit?: number
}

/**
 * BlockedDay updateManyAndReturn
 */
export type BlockedDayUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlockedDay
   */
  select?: Prisma.BlockedDaySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BlockedDay
   */
  omit?: Prisma.BlockedDayOmit<ExtArgs> | null
  /**
   * The data used to update BlockedDays.
   */
  data: Prisma.XOR<Prisma.BlockedDayUpdateManyMutationInput, Prisma.BlockedDayUncheckedUpdateManyInput>
  /**
   * Filter which BlockedDays to update
   */
  where?: Prisma.BlockedDayWhereInput
  /**
   * Limit how many BlockedDays to update.
   */
  limit?: number
}

/**
 * BlockedDay upsert
 */
export type BlockedDayUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlockedDay
   */
  select?: Prisma.BlockedDaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the BlockedDay
   */
  omit?: Prisma.BlockedDayOmit<ExtArgs> | null
  /**
   * The filter to search for the BlockedDay to update in case it exists.
   */
  where: Prisma.BlockedDayWhereUniqueInput
  /**
   * In case the BlockedDay found by the `where` argument doesn't exist, create a new BlockedDay with this data.
   */
  create: Prisma.XOR<Prisma.BlockedDayCreateInput, Prisma.BlockedDayUncheckedCreateInput>
  /**
   * In case the BlockedDay was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BlockedDayUpdateInput, Prisma.BlockedDayUncheckedUpdateInput>
}

/**
 * BlockedDay delete
 */
export type BlockedDayDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlockedDay
   */
  select?: Prisma.BlockedDaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the BlockedDay
   */
  omit?: Prisma.BlockedDayOmit<ExtArgs> | null
  /**
   * Filter which BlockedDay to delete.
   */
  where: Prisma.BlockedDayWhereUniqueInput
}

/**
 * BlockedDay deleteMany
 */
export type BlockedDayDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BlockedDays to delete
   */
  where?: Prisma.BlockedDayWhereInput
  /**
   * Limit how many BlockedDays to delete.
   */
  limit?: number
}

/**
 * BlockedDay without action
 */
export type BlockedDayDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BlockedDay
   */
  select?: Prisma.BlockedDaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the BlockedDay
   */
  omit?: Prisma.BlockedDayOmit<ExtArgs> | null
}
