
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TrainerPayment` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TrainerPayment
 * 
 */
export type TrainerPaymentModel = runtime.Types.Result.DefaultSelection<Prisma.$TrainerPaymentPayload>

export type AggregateTrainerPayment = {
  _count: TrainerPaymentCountAggregateOutputType | null
  _avg: TrainerPaymentAvgAggregateOutputType | null
  _sum: TrainerPaymentSumAggregateOutputType | null
  _min: TrainerPaymentMinAggregateOutputType | null
  _max: TrainerPaymentMaxAggregateOutputType | null
}

export type TrainerPaymentAvgAggregateOutputType = {
  amount: number | null
}

export type TrainerPaymentSumAggregateOutputType = {
  amount: number | null
}

export type TrainerPaymentMinAggregateOutputType = {
  id: string | null
  trainerId: string | null
  amount: number | null
  month: string | null
  note: string | null
  createdAt: Date | null
}

export type TrainerPaymentMaxAggregateOutputType = {
  id: string | null
  trainerId: string | null
  amount: number | null
  month: string | null
  note: string | null
  createdAt: Date | null
}

export type TrainerPaymentCountAggregateOutputType = {
  id: number
  trainerId: number
  amount: number
  month: number
  note: number
  createdAt: number
  _all: number
}


export type TrainerPaymentAvgAggregateInputType = {
  amount?: true
}

export type TrainerPaymentSumAggregateInputType = {
  amount?: true
}

export type TrainerPaymentMinAggregateInputType = {
  id?: true
  trainerId?: true
  amount?: true
  month?: true
  note?: true
  createdAt?: true
}

export type TrainerPaymentMaxAggregateInputType = {
  id?: true
  trainerId?: true
  amount?: true
  month?: true
  note?: true
  createdAt?: true
}

export type TrainerPaymentCountAggregateInputType = {
  id?: true
  trainerId?: true
  amount?: true
  month?: true
  note?: true
  createdAt?: true
  _all?: true
}

export type TrainerPaymentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TrainerPayment to aggregate.
   */
  where?: Prisma.TrainerPaymentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TrainerPayments to fetch.
   */
  orderBy?: Prisma.TrainerPaymentOrderByWithRelationInput | Prisma.TrainerPaymentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TrainerPaymentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TrainerPayments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TrainerPayments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TrainerPayments
  **/
  _count?: true | TrainerPaymentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TrainerPaymentAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TrainerPaymentSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TrainerPaymentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TrainerPaymentMaxAggregateInputType
}

export type GetTrainerPaymentAggregateType<T extends TrainerPaymentAggregateArgs> = {
      [P in keyof T & keyof AggregateTrainerPayment]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTrainerPayment[P]>
    : Prisma.GetScalarType<T[P], AggregateTrainerPayment[P]>
}




export type TrainerPaymentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TrainerPaymentWhereInput
  orderBy?: Prisma.TrainerPaymentOrderByWithAggregationInput | Prisma.TrainerPaymentOrderByWithAggregationInput[]
  by: Prisma.TrainerPaymentScalarFieldEnum[] | Prisma.TrainerPaymentScalarFieldEnum
  having?: Prisma.TrainerPaymentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TrainerPaymentCountAggregateInputType | true
  _avg?: TrainerPaymentAvgAggregateInputType
  _sum?: TrainerPaymentSumAggregateInputType
  _min?: TrainerPaymentMinAggregateInputType
  _max?: TrainerPaymentMaxAggregateInputType
}

export type TrainerPaymentGroupByOutputType = {
  id: string
  trainerId: string
  amount: number
  month: string
  note: string | null
  createdAt: Date
  _count: TrainerPaymentCountAggregateOutputType | null
  _avg: TrainerPaymentAvgAggregateOutputType | null
  _sum: TrainerPaymentSumAggregateOutputType | null
  _min: TrainerPaymentMinAggregateOutputType | null
  _max: TrainerPaymentMaxAggregateOutputType | null
}

export type GetTrainerPaymentGroupByPayload<T extends TrainerPaymentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TrainerPaymentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TrainerPaymentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TrainerPaymentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TrainerPaymentGroupByOutputType[P]>
      }
    >
  >



export type TrainerPaymentWhereInput = {
  AND?: Prisma.TrainerPaymentWhereInput | Prisma.TrainerPaymentWhereInput[]
  OR?: Prisma.TrainerPaymentWhereInput[]
  NOT?: Prisma.TrainerPaymentWhereInput | Prisma.TrainerPaymentWhereInput[]
  id?: Prisma.StringFilter<"TrainerPayment"> | string
  trainerId?: Prisma.StringFilter<"TrainerPayment"> | string
  amount?: Prisma.FloatFilter<"TrainerPayment"> | number
  month?: Prisma.StringFilter<"TrainerPayment"> | string
  note?: Prisma.StringNullableFilter<"TrainerPayment"> | string | null
  createdAt?: Prisma.DateTimeFilter<"TrainerPayment"> | Date | string
  trainer?: Prisma.XOR<Prisma.TrainerScalarRelationFilter, Prisma.TrainerWhereInput>
}

export type TrainerPaymentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  trainerId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  month?: Prisma.SortOrder
  note?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  trainer?: Prisma.TrainerOrderByWithRelationInput
}

export type TrainerPaymentWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TrainerPaymentWhereInput | Prisma.TrainerPaymentWhereInput[]
  OR?: Prisma.TrainerPaymentWhereInput[]
  NOT?: Prisma.TrainerPaymentWhereInput | Prisma.TrainerPaymentWhereInput[]
  trainerId?: Prisma.StringFilter<"TrainerPayment"> | string
  amount?: Prisma.FloatFilter<"TrainerPayment"> | number
  month?: Prisma.StringFilter<"TrainerPayment"> | string
  note?: Prisma.StringNullableFilter<"TrainerPayment"> | string | null
  createdAt?: Prisma.DateTimeFilter<"TrainerPayment"> | Date | string
  trainer?: Prisma.XOR<Prisma.TrainerScalarRelationFilter, Prisma.TrainerWhereInput>
}, "id">

export type TrainerPaymentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  trainerId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  month?: Prisma.SortOrder
  note?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.TrainerPaymentCountOrderByAggregateInput
  _avg?: Prisma.TrainerPaymentAvgOrderByAggregateInput
  _max?: Prisma.TrainerPaymentMaxOrderByAggregateInput
  _min?: Prisma.TrainerPaymentMinOrderByAggregateInput
  _sum?: Prisma.TrainerPaymentSumOrderByAggregateInput
}

export type TrainerPaymentScalarWhereWithAggregatesInput = {
  AND?: Prisma.TrainerPaymentScalarWhereWithAggregatesInput | Prisma.TrainerPaymentScalarWhereWithAggregatesInput[]
  OR?: Prisma.TrainerPaymentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TrainerPaymentScalarWhereWithAggregatesInput | Prisma.TrainerPaymentScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TrainerPayment"> | string
  trainerId?: Prisma.StringWithAggregatesFilter<"TrainerPayment"> | string
  amount?: Prisma.FloatWithAggregatesFilter<"TrainerPayment"> | number
  month?: Prisma.StringWithAggregatesFilter<"TrainerPayment"> | string
  note?: Prisma.StringNullableWithAggregatesFilter<"TrainerPayment"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TrainerPayment"> | Date | string
}

export type TrainerPaymentCreateInput = {
  id?: string
  amount: number
  month: string
  note?: string | null
  createdAt?: Date | string
  trainer: Prisma.TrainerCreateNestedOneWithoutPaymentsInput
}

export type TrainerPaymentUncheckedCreateInput = {
  id?: string
  trainerId: string
  amount: number
  month: string
  note?: string | null
  createdAt?: Date | string
}

export type TrainerPaymentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  month?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  trainer?: Prisma.TrainerUpdateOneRequiredWithoutPaymentsNestedInput
}

export type TrainerPaymentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  trainerId?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  month?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TrainerPaymentCreateManyInput = {
  id?: string
  trainerId: string
  amount: number
  month: string
  note?: string | null
  createdAt?: Date | string
}

export type TrainerPaymentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  month?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TrainerPaymentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  trainerId?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  month?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TrainerPaymentListRelationFilter = {
  every?: Prisma.TrainerPaymentWhereInput
  some?: Prisma.TrainerPaymentWhereInput
  none?: Prisma.TrainerPaymentWhereInput
}

export type TrainerPaymentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TrainerPaymentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  trainerId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  month?: Prisma.SortOrder
  note?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type TrainerPaymentAvgOrderByAggregateInput = {
  amount?: Prisma.SortOrder
}

export type TrainerPaymentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  trainerId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  month?: Prisma.SortOrder
  note?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type TrainerPaymentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  trainerId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  month?: Prisma.SortOrder
  note?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type TrainerPaymentSumOrderByAggregateInput = {
  amount?: Prisma.SortOrder
}

export type TrainerPaymentCreateNestedManyWithoutTrainerInput = {
  create?: Prisma.XOR<Prisma.TrainerPaymentCreateWithoutTrainerInput, Prisma.TrainerPaymentUncheckedCreateWithoutTrainerInput> | Prisma.TrainerPaymentCreateWithoutTrainerInput[] | Prisma.TrainerPaymentUncheckedCreateWithoutTrainerInput[]
  connectOrCreate?: Prisma.TrainerPaymentCreateOrConnectWithoutTrainerInput | Prisma.TrainerPaymentCreateOrConnectWithoutTrainerInput[]
  createMany?: Prisma.TrainerPaymentCreateManyTrainerInputEnvelope
  connect?: Prisma.TrainerPaymentWhereUniqueInput | Prisma.TrainerPaymentWhereUniqueInput[]
}

export type TrainerPaymentUncheckedCreateNestedManyWithoutTrainerInput = {
  create?: Prisma.XOR<Prisma.TrainerPaymentCreateWithoutTrainerInput, Prisma.TrainerPaymentUncheckedCreateWithoutTrainerInput> | Prisma.TrainerPaymentCreateWithoutTrainerInput[] | Prisma.TrainerPaymentUncheckedCreateWithoutTrainerInput[]
  connectOrCreate?: Prisma.TrainerPaymentCreateOrConnectWithoutTrainerInput | Prisma.TrainerPaymentCreateOrConnectWithoutTrainerInput[]
  createMany?: Prisma.TrainerPaymentCreateManyTrainerInputEnvelope
  connect?: Prisma.TrainerPaymentWhereUniqueInput | Prisma.TrainerPaymentWhereUniqueInput[]
}

export type TrainerPaymentUpdateManyWithoutTrainerNestedInput = {
  create?: Prisma.XOR<Prisma.TrainerPaymentCreateWithoutTrainerInput, Prisma.TrainerPaymentUncheckedCreateWithoutTrainerInput> | Prisma.TrainerPaymentCreateWithoutTrainerInput[] | Prisma.TrainerPaymentUncheckedCreateWithoutTrainerInput[]
  connectOrCreate?: Prisma.TrainerPaymentCreateOrConnectWithoutTrainerInput | Prisma.TrainerPaymentCreateOrConnectWithoutTrainerInput[]
  upsert?: Prisma.TrainerPaymentUpsertWithWhereUniqueWithoutTrainerInput | Prisma.TrainerPaymentUpsertWithWhereUniqueWithoutTrainerInput[]
  createMany?: Prisma.TrainerPaymentCreateManyTrainerInputEnvelope
  set?: Prisma.TrainerPaymentWhereUniqueInput | Prisma.TrainerPaymentWhereUniqueInput[]
  disconnect?: Prisma.TrainerPaymentWhereUniqueInput | Prisma.TrainerPaymentWhereUniqueInput[]
  delete?: Prisma.TrainerPaymentWhereUniqueInput | Prisma.TrainerPaymentWhereUniqueInput[]
  connect?: Prisma.TrainerPaymentWhereUniqueInput | Prisma.TrainerPaymentWhereUniqueInput[]
  update?: Prisma.TrainerPaymentUpdateWithWhereUniqueWithoutTrainerInput | Prisma.TrainerPaymentUpdateWithWhereUniqueWithoutTrainerInput[]
  updateMany?: Prisma.TrainerPaymentUpdateManyWithWhereWithoutTrainerInput | Prisma.TrainerPaymentUpdateManyWithWhereWithoutTrainerInput[]
  deleteMany?: Prisma.TrainerPaymentScalarWhereInput | Prisma.TrainerPaymentScalarWhereInput[]
}

export type TrainerPaymentUncheckedUpdateManyWithoutTrainerNestedInput = {
  create?: Prisma.XOR<Prisma.TrainerPaymentCreateWithoutTrainerInput, Prisma.TrainerPaymentUncheckedCreateWithoutTrainerInput> | Prisma.TrainerPaymentCreateWithoutTrainerInput[] | Prisma.TrainerPaymentUncheckedCreateWithoutTrainerInput[]
  connectOrCreate?: Prisma.TrainerPaymentCreateOrConnectWithoutTrainerInput | Prisma.TrainerPaymentCreateOrConnectWithoutTrainerInput[]
  upsert?: Prisma.TrainerPaymentUpsertWithWhereUniqueWithoutTrainerInput | Prisma.TrainerPaymentUpsertWithWhereUniqueWithoutTrainerInput[]
  createMany?: Prisma.TrainerPaymentCreateManyTrainerInputEnvelope
  set?: Prisma.TrainerPaymentWhereUniqueInput | Prisma.TrainerPaymentWhereUniqueInput[]
  disconnect?: Prisma.TrainerPaymentWhereUniqueInput | Prisma.TrainerPaymentWhereUniqueInput[]
  delete?: Prisma.TrainerPaymentWhereUniqueInput | Prisma.TrainerPaymentWhereUniqueInput[]
  connect?: Prisma.TrainerPaymentWhereUniqueInput | Prisma.TrainerPaymentWhereUniqueInput[]
  update?: Prisma.TrainerPaymentUpdateWithWhereUniqueWithoutTrainerInput | Prisma.TrainerPaymentUpdateWithWhereUniqueWithoutTrainerInput[]
  updateMany?: Prisma.TrainerPaymentUpdateManyWithWhereWithoutTrainerInput | Prisma.TrainerPaymentUpdateManyWithWhereWithoutTrainerInput[]
  deleteMany?: Prisma.TrainerPaymentScalarWhereInput | Prisma.TrainerPaymentScalarWhereInput[]
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type TrainerPaymentCreateWithoutTrainerInput = {
  id?: string
  amount: number
  month: string
  note?: string | null
  createdAt?: Date | string
}

export type TrainerPaymentUncheckedCreateWithoutTrainerInput = {
  id?: string
  amount: number
  month: string
  note?: string | null
  createdAt?: Date | string
}

export type TrainerPaymentCreateOrConnectWithoutTrainerInput = {
  where: Prisma.TrainerPaymentWhereUniqueInput
  create: Prisma.XOR<Prisma.TrainerPaymentCreateWithoutTrainerInput, Prisma.TrainerPaymentUncheckedCreateWithoutTrainerInput>
}

export type TrainerPaymentCreateManyTrainerInputEnvelope = {
  data: Prisma.TrainerPaymentCreateManyTrainerInput | Prisma.TrainerPaymentCreateManyTrainerInput[]
}

export type TrainerPaymentUpsertWithWhereUniqueWithoutTrainerInput = {
  where: Prisma.TrainerPaymentWhereUniqueInput
  update: Prisma.XOR<Prisma.TrainerPaymentUpdateWithoutTrainerInput, Prisma.TrainerPaymentUncheckedUpdateWithoutTrainerInput>
  create: Prisma.XOR<Prisma.TrainerPaymentCreateWithoutTrainerInput, Prisma.TrainerPaymentUncheckedCreateWithoutTrainerInput>
}

export type TrainerPaymentUpdateWithWhereUniqueWithoutTrainerInput = {
  where: Prisma.TrainerPaymentWhereUniqueInput
  data: Prisma.XOR<Prisma.TrainerPaymentUpdateWithoutTrainerInput, Prisma.TrainerPaymentUncheckedUpdateWithoutTrainerInput>
}

export type TrainerPaymentUpdateManyWithWhereWithoutTrainerInput = {
  where: Prisma.TrainerPaymentScalarWhereInput
  data: Prisma.XOR<Prisma.TrainerPaymentUpdateManyMutationInput, Prisma.TrainerPaymentUncheckedUpdateManyWithoutTrainerInput>
}

export type TrainerPaymentScalarWhereInput = {
  AND?: Prisma.TrainerPaymentScalarWhereInput | Prisma.TrainerPaymentScalarWhereInput[]
  OR?: Prisma.TrainerPaymentScalarWhereInput[]
  NOT?: Prisma.TrainerPaymentScalarWhereInput | Prisma.TrainerPaymentScalarWhereInput[]
  id?: Prisma.StringFilter<"TrainerPayment"> | string
  trainerId?: Prisma.StringFilter<"TrainerPayment"> | string
  amount?: Prisma.FloatFilter<"TrainerPayment"> | number
  month?: Prisma.StringFilter<"TrainerPayment"> | string
  note?: Prisma.StringNullableFilter<"TrainerPayment"> | string | null
  createdAt?: Prisma.DateTimeFilter<"TrainerPayment"> | Date | string
}

export type TrainerPaymentCreateManyTrainerInput = {
  id?: string
  amount: number
  month: string
  note?: string | null
  createdAt?: Date | string
}

export type TrainerPaymentUpdateWithoutTrainerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  month?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TrainerPaymentUncheckedUpdateWithoutTrainerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  month?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TrainerPaymentUncheckedUpdateManyWithoutTrainerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  month?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type TrainerPaymentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  trainerId?: boolean
  amount?: boolean
  month?: boolean
  note?: boolean
  createdAt?: boolean
  trainer?: boolean | Prisma.TrainerDefaultArgs<ExtArgs>
}, ExtArgs["result"]["trainerPayment"]>

export type TrainerPaymentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  trainerId?: boolean
  amount?: boolean
  month?: boolean
  note?: boolean
  createdAt?: boolean
  trainer?: boolean | Prisma.TrainerDefaultArgs<ExtArgs>
}, ExtArgs["result"]["trainerPayment"]>

export type TrainerPaymentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  trainerId?: boolean
  amount?: boolean
  month?: boolean
  note?: boolean
  createdAt?: boolean
  trainer?: boolean | Prisma.TrainerDefaultArgs<ExtArgs>
}, ExtArgs["result"]["trainerPayment"]>

export type TrainerPaymentSelectScalar = {
  id?: boolean
  trainerId?: boolean
  amount?: boolean
  month?: boolean
  note?: boolean
  createdAt?: boolean
}

export type TrainerPaymentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "trainerId" | "amount" | "month" | "note" | "createdAt", ExtArgs["result"]["trainerPayment"]>
export type TrainerPaymentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  trainer?: boolean | Prisma.TrainerDefaultArgs<ExtArgs>
}
export type TrainerPaymentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  trainer?: boolean | Prisma.TrainerDefaultArgs<ExtArgs>
}
export type TrainerPaymentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  trainer?: boolean | Prisma.TrainerDefaultArgs<ExtArgs>
}

export type $TrainerPaymentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TrainerPayment"
  objects: {
    trainer: Prisma.$TrainerPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    trainerId: string
    amount: number
    month: string
    note: string | null
    createdAt: Date
  }, ExtArgs["result"]["trainerPayment"]>
  composites: {}
}

export type TrainerPaymentGetPayload<S extends boolean | null | undefined | TrainerPaymentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TrainerPaymentPayload, S>

export type TrainerPaymentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TrainerPaymentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TrainerPaymentCountAggregateInputType | true
  }

export interface TrainerPaymentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TrainerPayment'], meta: { name: 'TrainerPayment' } }
  /**
   * Find zero or one TrainerPayment that matches the filter.
   * @param {TrainerPaymentFindUniqueArgs} args - Arguments to find a TrainerPayment
   * @example
   * // Get one TrainerPayment
   * const trainerPayment = await prisma.trainerPayment.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TrainerPaymentFindUniqueArgs>(args: Prisma.SelectSubset<T, TrainerPaymentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TrainerPaymentClient<runtime.Types.Result.GetResult<Prisma.$TrainerPaymentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TrainerPayment that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TrainerPaymentFindUniqueOrThrowArgs} args - Arguments to find a TrainerPayment
   * @example
   * // Get one TrainerPayment
   * const trainerPayment = await prisma.trainerPayment.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TrainerPaymentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TrainerPaymentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TrainerPaymentClient<runtime.Types.Result.GetResult<Prisma.$TrainerPaymentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TrainerPayment that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TrainerPaymentFindFirstArgs} args - Arguments to find a TrainerPayment
   * @example
   * // Get one TrainerPayment
   * const trainerPayment = await prisma.trainerPayment.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TrainerPaymentFindFirstArgs>(args?: Prisma.SelectSubset<T, TrainerPaymentFindFirstArgs<ExtArgs>>): Prisma.Prisma__TrainerPaymentClient<runtime.Types.Result.GetResult<Prisma.$TrainerPaymentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TrainerPayment that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TrainerPaymentFindFirstOrThrowArgs} args - Arguments to find a TrainerPayment
   * @example
   * // Get one TrainerPayment
   * const trainerPayment = await prisma.trainerPayment.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TrainerPaymentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TrainerPaymentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TrainerPaymentClient<runtime.Types.Result.GetResult<Prisma.$TrainerPaymentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TrainerPayments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TrainerPaymentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TrainerPayments
   * const trainerPayments = await prisma.trainerPayment.findMany()
   * 
   * // Get first 10 TrainerPayments
   * const trainerPayments = await prisma.trainerPayment.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const trainerPaymentWithIdOnly = await prisma.trainerPayment.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TrainerPaymentFindManyArgs>(args?: Prisma.SelectSubset<T, TrainerPaymentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TrainerPaymentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TrainerPayment.
   * @param {TrainerPaymentCreateArgs} args - Arguments to create a TrainerPayment.
   * @example
   * // Create one TrainerPayment
   * const TrainerPayment = await prisma.trainerPayment.create({
   *   data: {
   *     // ... data to create a TrainerPayment
   *   }
   * })
   * 
   */
  create<T extends TrainerPaymentCreateArgs>(args: Prisma.SelectSubset<T, TrainerPaymentCreateArgs<ExtArgs>>): Prisma.Prisma__TrainerPaymentClient<runtime.Types.Result.GetResult<Prisma.$TrainerPaymentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TrainerPayments.
   * @param {TrainerPaymentCreateManyArgs} args - Arguments to create many TrainerPayments.
   * @example
   * // Create many TrainerPayments
   * const trainerPayment = await prisma.trainerPayment.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TrainerPaymentCreateManyArgs>(args?: Prisma.SelectSubset<T, TrainerPaymentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TrainerPayments and returns the data saved in the database.
   * @param {TrainerPaymentCreateManyAndReturnArgs} args - Arguments to create many TrainerPayments.
   * @example
   * // Create many TrainerPayments
   * const trainerPayment = await prisma.trainerPayment.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TrainerPayments and only return the `id`
   * const trainerPaymentWithIdOnly = await prisma.trainerPayment.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TrainerPaymentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TrainerPaymentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TrainerPaymentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TrainerPayment.
   * @param {TrainerPaymentDeleteArgs} args - Arguments to delete one TrainerPayment.
   * @example
   * // Delete one TrainerPayment
   * const TrainerPayment = await prisma.trainerPayment.delete({
   *   where: {
   *     // ... filter to delete one TrainerPayment
   *   }
   * })
   * 
   */
  delete<T extends TrainerPaymentDeleteArgs>(args: Prisma.SelectSubset<T, TrainerPaymentDeleteArgs<ExtArgs>>): Prisma.Prisma__TrainerPaymentClient<runtime.Types.Result.GetResult<Prisma.$TrainerPaymentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TrainerPayment.
   * @param {TrainerPaymentUpdateArgs} args - Arguments to update one TrainerPayment.
   * @example
   * // Update one TrainerPayment
   * const trainerPayment = await prisma.trainerPayment.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TrainerPaymentUpdateArgs>(args: Prisma.SelectSubset<T, TrainerPaymentUpdateArgs<ExtArgs>>): Prisma.Prisma__TrainerPaymentClient<runtime.Types.Result.GetResult<Prisma.$TrainerPaymentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TrainerPayments.
   * @param {TrainerPaymentDeleteManyArgs} args - Arguments to filter TrainerPayments to delete.
   * @example
   * // Delete a few TrainerPayments
   * const { count } = await prisma.trainerPayment.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TrainerPaymentDeleteManyArgs>(args?: Prisma.SelectSubset<T, TrainerPaymentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TrainerPayments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TrainerPaymentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TrainerPayments
   * const trainerPayment = await prisma.trainerPayment.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TrainerPaymentUpdateManyArgs>(args: Prisma.SelectSubset<T, TrainerPaymentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TrainerPayments and returns the data updated in the database.
   * @param {TrainerPaymentUpdateManyAndReturnArgs} args - Arguments to update many TrainerPayments.
   * @example
   * // Update many TrainerPayments
   * const trainerPayment = await prisma.trainerPayment.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TrainerPayments and only return the `id`
   * const trainerPaymentWithIdOnly = await prisma.trainerPayment.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TrainerPaymentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TrainerPaymentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TrainerPaymentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TrainerPayment.
   * @param {TrainerPaymentUpsertArgs} args - Arguments to update or create a TrainerPayment.
   * @example
   * // Update or create a TrainerPayment
   * const trainerPayment = await prisma.trainerPayment.upsert({
   *   create: {
   *     // ... data to create a TrainerPayment
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TrainerPayment we want to update
   *   }
   * })
   */
  upsert<T extends TrainerPaymentUpsertArgs>(args: Prisma.SelectSubset<T, TrainerPaymentUpsertArgs<ExtArgs>>): Prisma.Prisma__TrainerPaymentClient<runtime.Types.Result.GetResult<Prisma.$TrainerPaymentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TrainerPayments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TrainerPaymentCountArgs} args - Arguments to filter TrainerPayments to count.
   * @example
   * // Count the number of TrainerPayments
   * const count = await prisma.trainerPayment.count({
   *   where: {
   *     // ... the filter for the TrainerPayments we want to count
   *   }
   * })
  **/
  count<T extends TrainerPaymentCountArgs>(
    args?: Prisma.Subset<T, TrainerPaymentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TrainerPaymentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TrainerPayment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TrainerPaymentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TrainerPaymentAggregateArgs>(args: Prisma.Subset<T, TrainerPaymentAggregateArgs>): Prisma.PrismaPromise<GetTrainerPaymentAggregateType<T>>

  /**
   * Group by TrainerPayment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TrainerPaymentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TrainerPaymentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TrainerPaymentGroupByArgs['orderBy'] }
      : { orderBy?: TrainerPaymentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TrainerPaymentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTrainerPaymentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TrainerPayment model
 */
readonly fields: TrainerPaymentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TrainerPayment.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TrainerPaymentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  trainer<T extends Prisma.TrainerDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TrainerDefaultArgs<ExtArgs>>): Prisma.Prisma__TrainerClient<runtime.Types.Result.GetResult<Prisma.$TrainerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TrainerPayment model
 */
export interface TrainerPaymentFieldRefs {
  readonly id: Prisma.FieldRef<"TrainerPayment", 'String'>
  readonly trainerId: Prisma.FieldRef<"TrainerPayment", 'String'>
  readonly amount: Prisma.FieldRef<"TrainerPayment", 'Float'>
  readonly month: Prisma.FieldRef<"TrainerPayment", 'String'>
  readonly note: Prisma.FieldRef<"TrainerPayment", 'String'>
  readonly createdAt: Prisma.FieldRef<"TrainerPayment", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TrainerPayment findUnique
 */
export type TrainerPaymentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrainerPayment
   */
  select?: Prisma.TrainerPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TrainerPayment
   */
  omit?: Prisma.TrainerPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TrainerPaymentInclude<ExtArgs> | null
  /**
   * Filter, which TrainerPayment to fetch.
   */
  where: Prisma.TrainerPaymentWhereUniqueInput
}

/**
 * TrainerPayment findUniqueOrThrow
 */
export type TrainerPaymentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrainerPayment
   */
  select?: Prisma.TrainerPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TrainerPayment
   */
  omit?: Prisma.TrainerPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TrainerPaymentInclude<ExtArgs> | null
  /**
   * Filter, which TrainerPayment to fetch.
   */
  where: Prisma.TrainerPaymentWhereUniqueInput
}

/**
 * TrainerPayment findFirst
 */
export type TrainerPaymentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrainerPayment
   */
  select?: Prisma.TrainerPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TrainerPayment
   */
  omit?: Prisma.TrainerPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TrainerPaymentInclude<ExtArgs> | null
  /**
   * Filter, which TrainerPayment to fetch.
   */
  where?: Prisma.TrainerPaymentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TrainerPayments to fetch.
   */
  orderBy?: Prisma.TrainerPaymentOrderByWithRelationInput | Prisma.TrainerPaymentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TrainerPayments.
   */
  cursor?: Prisma.TrainerPaymentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TrainerPayments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TrainerPayments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TrainerPayments.
   */
  distinct?: Prisma.TrainerPaymentScalarFieldEnum | Prisma.TrainerPaymentScalarFieldEnum[]
}

/**
 * TrainerPayment findFirstOrThrow
 */
export type TrainerPaymentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrainerPayment
   */
  select?: Prisma.TrainerPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TrainerPayment
   */
  omit?: Prisma.TrainerPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TrainerPaymentInclude<ExtArgs> | null
  /**
   * Filter, which TrainerPayment to fetch.
   */
  where?: Prisma.TrainerPaymentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TrainerPayments to fetch.
   */
  orderBy?: Prisma.TrainerPaymentOrderByWithRelationInput | Prisma.TrainerPaymentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TrainerPayments.
   */
  cursor?: Prisma.TrainerPaymentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TrainerPayments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TrainerPayments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TrainerPayments.
   */
  distinct?: Prisma.TrainerPaymentScalarFieldEnum | Prisma.TrainerPaymentScalarFieldEnum[]
}

/**
 * TrainerPayment findMany
 */
export type TrainerPaymentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrainerPayment
   */
  select?: Prisma.TrainerPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TrainerPayment
   */
  omit?: Prisma.TrainerPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TrainerPaymentInclude<ExtArgs> | null
  /**
   * Filter, which TrainerPayments to fetch.
   */
  where?: Prisma.TrainerPaymentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TrainerPayments to fetch.
   */
  orderBy?: Prisma.TrainerPaymentOrderByWithRelationInput | Prisma.TrainerPaymentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TrainerPayments.
   */
  cursor?: Prisma.TrainerPaymentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TrainerPayments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TrainerPayments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TrainerPayments.
   */
  distinct?: Prisma.TrainerPaymentScalarFieldEnum | Prisma.TrainerPaymentScalarFieldEnum[]
}

/**
 * TrainerPayment create
 */
export type TrainerPaymentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrainerPayment
   */
  select?: Prisma.TrainerPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TrainerPayment
   */
  omit?: Prisma.TrainerPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TrainerPaymentInclude<ExtArgs> | null
  /**
   * The data needed to create a TrainerPayment.
   */
  data: Prisma.XOR<Prisma.TrainerPaymentCreateInput, Prisma.TrainerPaymentUncheckedCreateInput>
}

/**
 * TrainerPayment createMany
 */
export type TrainerPaymentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TrainerPayments.
   */
  data: Prisma.TrainerPaymentCreateManyInput | Prisma.TrainerPaymentCreateManyInput[]
}

/**
 * TrainerPayment createManyAndReturn
 */
export type TrainerPaymentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrainerPayment
   */
  select?: Prisma.TrainerPaymentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TrainerPayment
   */
  omit?: Prisma.TrainerPaymentOmit<ExtArgs> | null
  /**
   * The data used to create many TrainerPayments.
   */
  data: Prisma.TrainerPaymentCreateManyInput | Prisma.TrainerPaymentCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TrainerPaymentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TrainerPayment update
 */
export type TrainerPaymentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrainerPayment
   */
  select?: Prisma.TrainerPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TrainerPayment
   */
  omit?: Prisma.TrainerPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TrainerPaymentInclude<ExtArgs> | null
  /**
   * The data needed to update a TrainerPayment.
   */
  data: Prisma.XOR<Prisma.TrainerPaymentUpdateInput, Prisma.TrainerPaymentUncheckedUpdateInput>
  /**
   * Choose, which TrainerPayment to update.
   */
  where: Prisma.TrainerPaymentWhereUniqueInput
}

/**
 * TrainerPayment updateMany
 */
export type TrainerPaymentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TrainerPayments.
   */
  data: Prisma.XOR<Prisma.TrainerPaymentUpdateManyMutationInput, Prisma.TrainerPaymentUncheckedUpdateManyInput>
  /**
   * Filter which TrainerPayments to update
   */
  where?: Prisma.TrainerPaymentWhereInput
  /**
   * Limit how many TrainerPayments to update.
   */
  limit?: number
}

/**
 * TrainerPayment updateManyAndReturn
 */
export type TrainerPaymentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrainerPayment
   */
  select?: Prisma.TrainerPaymentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TrainerPayment
   */
  omit?: Prisma.TrainerPaymentOmit<ExtArgs> | null
  /**
   * The data used to update TrainerPayments.
   */
  data: Prisma.XOR<Prisma.TrainerPaymentUpdateManyMutationInput, Prisma.TrainerPaymentUncheckedUpdateManyInput>
  /**
   * Filter which TrainerPayments to update
   */
  where?: Prisma.TrainerPaymentWhereInput
  /**
   * Limit how many TrainerPayments to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TrainerPaymentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TrainerPayment upsert
 */
export type TrainerPaymentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrainerPayment
   */
  select?: Prisma.TrainerPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TrainerPayment
   */
  omit?: Prisma.TrainerPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TrainerPaymentInclude<ExtArgs> | null
  /**
   * The filter to search for the TrainerPayment to update in case it exists.
   */
  where: Prisma.TrainerPaymentWhereUniqueInput
  /**
   * In case the TrainerPayment found by the `where` argument doesn't exist, create a new TrainerPayment with this data.
   */
  create: Prisma.XOR<Prisma.TrainerPaymentCreateInput, Prisma.TrainerPaymentUncheckedCreateInput>
  /**
   * In case the TrainerPayment was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TrainerPaymentUpdateInput, Prisma.TrainerPaymentUncheckedUpdateInput>
}

/**
 * TrainerPayment delete
 */
export type TrainerPaymentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrainerPayment
   */
  select?: Prisma.TrainerPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TrainerPayment
   */
  omit?: Prisma.TrainerPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TrainerPaymentInclude<ExtArgs> | null
  /**
   * Filter which TrainerPayment to delete.
   */
  where: Prisma.TrainerPaymentWhereUniqueInput
}

/**
 * TrainerPayment deleteMany
 */
export type TrainerPaymentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TrainerPayments to delete
   */
  where?: Prisma.TrainerPaymentWhereInput
  /**
   * Limit how many TrainerPayments to delete.
   */
  limit?: number
}

/**
 * TrainerPayment without action
 */
export type TrainerPaymentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrainerPayment
   */
  select?: Prisma.TrainerPaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TrainerPayment
   */
  omit?: Prisma.TrainerPaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TrainerPaymentInclude<ExtArgs> | null
}
