
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  PasswordResetToken: 'PasswordResetToken',
  Trainer: 'Trainer',
  BlockedDay: 'BlockedDay',
  TrainerPayment: 'TrainerPayment',
  Expense: 'Expense',
  TimeSlot: 'TimeSlot',
  Booking: 'Booking',
  AdditionalService: 'AdditionalService',
  BookingService: 'BookingService'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  password: 'password',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const PasswordResetTokenScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  token: 'token',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt'
} as const

export type PasswordResetTokenScalarFieldEnum = (typeof PasswordResetTokenScalarFieldEnum)[keyof typeof PasswordResetTokenScalarFieldEnum]


export const TrainerScalarFieldEnum = {
  id: 'id',
  name: 'name',
  whatsapp: 'whatsapp',
  userId: 'userId',
  commissionRate: 'commissionRate',
  color: 'color',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TrainerScalarFieldEnum = (typeof TrainerScalarFieldEnum)[keyof typeof TrainerScalarFieldEnum]


export const BlockedDayScalarFieldEnum = {
  id: 'id',
  date: 'date',
  reason: 'reason',
  createdAt: 'createdAt'
} as const

export type BlockedDayScalarFieldEnum = (typeof BlockedDayScalarFieldEnum)[keyof typeof BlockedDayScalarFieldEnum]


export const TrainerPaymentScalarFieldEnum = {
  id: 'id',
  trainerId: 'trainerId',
  amount: 'amount',
  month: 'month',
  note: 'note',
  createdAt: 'createdAt'
} as const

export type TrainerPaymentScalarFieldEnum = (typeof TrainerPaymentScalarFieldEnum)[keyof typeof TrainerPaymentScalarFieldEnum]


export const ExpenseScalarFieldEnum = {
  id: 'id',
  amount: 'amount',
  category: 'category',
  description: 'description',
  date: 'date',
  createdAt: 'createdAt'
} as const

export type ExpenseScalarFieldEnum = (typeof ExpenseScalarFieldEnum)[keyof typeof ExpenseScalarFieldEnum]


export const TimeSlotScalarFieldEnum = {
  id: 'id',
  date: 'date',
  startTime: 'startTime',
  endTime: 'endTime',
  trainerId: 'trainerId',
  assistantId: 'assistantId',
  maxCapacity: 'maxCapacity',
  price: 'price',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TimeSlotScalarFieldEnum = (typeof TimeSlotScalarFieldEnum)[keyof typeof TimeSlotScalarFieldEnum]


export const BookingScalarFieldEnum = {
  id: 'id',
  slotId: 'slotId',
  clientName: 'clientName',
  clientEmail: 'clientEmail',
  clientPhone: 'clientPhone',
  clientTelegram: 'clientTelegram',
  status: 'status',
  paymentType: 'paymentType',
  paymentStatus: 'paymentStatus',
  ticketCode: 'ticketCode',
  checkedIn: 'checkedIn',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BookingScalarFieldEnum = (typeof BookingScalarFieldEnum)[keyof typeof BookingScalarFieldEnum]


export const AdditionalServiceScalarFieldEnum = {
  id: 'id',
  name: 'name',
  price: 'price',
  active: 'active'
} as const

export type AdditionalServiceScalarFieldEnum = (typeof AdditionalServiceScalarFieldEnum)[keyof typeof AdditionalServiceScalarFieldEnum]


export const BookingServiceScalarFieldEnum = {
  id: 'id',
  bookingId: 'bookingId',
  serviceId: 'serviceId'
} as const

export type BookingServiceScalarFieldEnum = (typeof BookingServiceScalarFieldEnum)[keyof typeof BookingServiceScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

